name: plads_2_0
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  provider: ^6.1.2
  intl: ^0.19.0
  table_calendar: ^3.1.2
  qr_flutter: ^4.1.0
  fl_chart: ^0.69.0
  shared_preferences: ^2.5.4
  font_awesome_flutter: ^10.12.0
  url_launcher: ^6.3.2
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  mobile_scanner: ^5.1.0
  uuid: ^4.5.2
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter_web: ^0.5.14+3
  google_sign_in: ^6.2.1
  firebase_storage: ^12.4.10
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_app.png"
  min_sdk_android: 21 
  remove_alpha_ios: true

flutter_native_splash:
  color: "#000000"
  image: "assets/images/logo_app.png"
  android_12:
    image: "assets/images/logo_app.png"
    color: "#000000"
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
